import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation/Navigation";
import Footer from "@/components/footer/Footer";
import { Providers } from "@/redux/Providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Toaster
            position="bottom-right"
            reverseOrder={false}
            toastOptions={{ duration: 7500 }}
          />
          <Navigation />
          <div className="px-[1rem] md:px-[4rem] py-[1rem]">{children}</div>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
